export const PHYSICS_CONFIG = Object.freeze({
  FIXED_TIME_STEP: 1 / 60,
  MAX_SUB_STEPS: 5,
  LINEAR_DAMPING: 1.1,
  ANGULAR_DAMPING: 1.55,
  FIXTURE_FRICTION: 0.55,
  FIXTURE_RESTITUTION: 0.35,
  MAX_DRAG_DISTANCE: 180,
  MAX_LAUNCH_SPEED: 22,
  STOP_LINEAR_SPEED: 0.75,
  STOP_ANGULAR_SPEED: 0.75,
  STOP_STABLE_TIME_MS: 150,
  MAX_SIMULATION_STEPS: 240,
});
