export const PHYSICS_CONFIG = Object.freeze({
  FIXED_TIME_STEP: 1 / 60,
  MAX_SUB_STEPS: 5,
  LINEAR_DAMPING: 0.8,
  ANGULAR_DAMPING: 1.35,
  FIXTURE_FRICTION: 0.55,
  FIXTURE_RESTITUTION: 0.35,
  MAX_DRAG_DISTANCE: 180,
  MAX_LAUNCH_SPEED: 22,
  STOP_LINEAR_SPEED: 0.05,
  STOP_ANGULAR_SPEED: 0.05,
  STOP_STABLE_TIME_MS: 300,
});
